base_url = "https://narodr.github.io"
title = "Nicolás Á. Rodríguez"
author = "narodr"

compile_sass = true
generate_feeds = false

theme = "lightspeed"

[markdown]

highlight_code = true
highlight_theme = "gruvbox-light"

[extra]

footer_links = [
    {url = "$BASE_URL", name = "Archive"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"}
]

footer_credits = false